/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package flamefeed.BreedingTracker.src.client.gui;

import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author Anedaar
 */
public class GuiTest extends javax.swing.JFrame {

    /**
     * Creates new form GuiTest
     */
    public GuiTest() {
        initComponents();
        JPanel middle = new JPanel();
        middle.setLayout(new BoxLayout(middle, javax.swing.BoxLayout.PAGE_AXIS));
        JPanel blubb = new SpeciesPanel(null);
        blubb.setVisible(true);
        middle.add(blubb);
        getContentPane().add(middle);
        
        JPanel mutation = new MutationPanel(null);
        getContentPane().add(mutation);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        panelShow = new javax.swing.JPanel();
        buttonShow = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        panelDetails = new javax.swing.JPanel();
        checkFound = new javax.swing.JCheckBox();
        checkSerum = new javax.swing.JCheckBox();
        labelTier = new javax.swing.JLabel();
        labelSteps = new javax.swing.JLabel();
        buttonToDo = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setAlignmentX(0.5F);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1formMouseReleased(evt);
            }
        });
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        labelName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setText("Fixed");
        labelName.setAlignmentX(0.5F);
        labelName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelName.setMaximumSize(new java.awt.Dimension(80, 25));
        labelName.setMinimumSize(new java.awt.Dimension(80, 25));
        labelName.setPreferredSize(new java.awt.Dimension(80, 25));
        jPanel1.add(labelName);

        panelShow.setLayout(new javax.swing.BoxLayout(panelShow, javax.swing.BoxLayout.LINE_AXIS));

        buttonShow.setMaximumSize(new java.awt.Dimension(20, 20));
        buttonShow.setMinimumSize(new java.awt.Dimension(20, 20));
        buttonShow.setPreferredSize(new java.awt.Dimension(20, 20));
        buttonShow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonShowStateChanged(evt);
            }
        });
        panelShow.add(buttonShow);

        jLabel1.setText("Details");
        panelShow.add(jLabel1);

        jPanel1.add(panelShow);

        panelDetails.setMaximumSize(new java.awt.Dimension(74, 110));
        panelDetails.setMinimumSize(new java.awt.Dimension(74, 110));
        panelDetails.setPreferredSize(new java.awt.Dimension(74, 110));
        panelDetails.setLayout(new javax.swing.BoxLayout(panelDetails, javax.swing.BoxLayout.PAGE_AXIS));

        checkFound.setText("found");
        checkFound.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkFoundStateChanged(evt);
            }
        });
        panelDetails.add(checkFound);

        checkSerum.setText("serum");
        checkSerum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkSerumStateChanged(evt);
            }
        });
        panelDetails.add(checkSerum);

        labelTier.setText("Tier: 00");
        panelDetails.add(labelTier);

        labelSteps.setText("Steps to go: 00");
        panelDetails.add(labelSteps);

        buttonToDo.setText("ToDo");
        buttonToDo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonToDoStateChanged(evt);
            }
        });
        panelDetails.add(buttonToDo);

        jPanel1.add(panelDetails);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonShowStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonShowStateChanged
        this.panelDetails.setVisible(buttonShow.isSelected());
    }//GEN-LAST:event_buttonShowStateChanged

    private void checkFoundStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkFoundStateChanged
//        species.setFound(checkFound.isSelected());
    }//GEN-LAST:event_checkFoundStateChanged

    private void checkSerumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkSerumStateChanged
//        species.setSerum(checkSerum.isSelected());
    }//GEN-LAST:event_checkSerumStateChanged

    private void buttonToDoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonToDoStateChanged
//        species.setToDo(buttonToDo.isSelected());
    }//GEN-LAST:event_buttonToDoStateChanged

    private void jPanel1formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1formMouseReleased
//        BreedingJFrame.getInstance().setSpecies(species);
    }//GEN-LAST:event_jPanel1formMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonShow;
    private javax.swing.JToggleButton buttonToDo;
    private javax.swing.JCheckBox checkFound;
    private javax.swing.JCheckBox checkSerum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSteps;
    private javax.swing.JLabel labelTier;
    private javax.swing.JPanel panelDetails;
    private javax.swing.JPanel panelShow;
    // End of variables declaration//GEN-END:variables
}
