/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flamefeed.BreedingTracker.src.client.gui;

import flamefeed.BreedingTracker.src.client.EventLogger;
import flamefeed.BreedingTracker.src.client.breeding.ITrackedSpeciesListener;
import flamefeed.BreedingTracker.src.client.breeding.SpeciesHandler.TrackedSpecies;
import java.awt.Dimension;

/**
 *
 * @author Anedaar
 */
public class SpeciesPanel extends javax.swing.JPanel implements ITrackedSpeciesListener {

    private TrackedSpecies species;

    /**
     * Creates new form SpeciesPanel
     *
     * @param species the species this panel displays
     */
    public SpeciesPanel(TrackedSpecies species) {
        initComponents();
        setSpecies(species);

        this.panelDetails.setVisible(false);

    }

    /**
     * Sets a new Species for this Panel, call with 'null' to empty
     *
     * @param spec
     */
    public void setSpecies(TrackedSpecies spec) {

        if (this.species != null) {
            this.species.unregister(this);
        }

        if (spec != null) {
            this.species = spec;
            this.species.register(this);
            this.setVisible(true);
            updateValues();
        } else {
            this.setVisible(false);
        }
        this.repaint();
    }

    private void updateValues() {
        labelName.setText(species.getSpecies().getName());
        labelTier.setText("Tier: " + species.getTier());
        labelSteps.setText("Steps to go: " + species.getSteps());

        checkFound.setSelected(species.isFound());
        checkSerum.setSelected(species.isSerum());
        buttonToDo.setSelected(species.isToDo());

        this.panelDetails.doLayout();
        this.repaint();

//        this.setMinimumSize(new Dimension());
    }

    @Override
    public void speciesUpdated(Value v) {
        switch (v) {
            case STEPS:
                labelSteps.setText("Steps to go: " + species.getSteps());
                break;
            case FOUND:
                checkFound.setSelected(species.isFound());
                break;
            case SERUM:
                checkSerum.setSelected(species.isSerum());
                break;
            case TODO:
                buttonToDo.setSelected(species.isToDo());
                break;

        }

    }

    @Override
    public Dimension getSize() {
        return super.getMinimumSize(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Dimension getPreferredSize() {
        return super.getMinimumSize(); //To change body of generated methods, choose Tools | Templates.
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new javax.swing.JLabel();
        panelShow = new javax.swing.JPanel();
        buttonShow = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        panelDetails = new javax.swing.JPanel();
        checkFound = new javax.swing.JCheckBox();
        checkSerum = new javax.swing.JCheckBox();
        labelTier = new javax.swing.JLabel();
        labelSteps = new javax.swing.JLabel();
        buttonToDo = new javax.swing.JToggleButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        labelName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setText("SpeciesName");
        labelName.setAlignmentX(0.5F);
        labelName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelName.setMaximumSize(new java.awt.Dimension(80, 25));
        labelName.setMinimumSize(new java.awt.Dimension(80, 25));
        labelName.setPreferredSize(new java.awt.Dimension(80, 25));
        add(labelName);

        panelShow.setLayout(new javax.swing.BoxLayout(panelShow, javax.swing.BoxLayout.LINE_AXIS));

        buttonShow.setMaximumSize(new java.awt.Dimension(20, 20));
        buttonShow.setMinimumSize(new java.awt.Dimension(20, 20));
        buttonShow.setPreferredSize(new java.awt.Dimension(20, 20));
        buttonShow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonShowStateChanged(evt);
            }
        });
        panelShow.add(buttonShow);

        jLabel1.setText("Details");
        panelShow.add(jLabel1);

        add(panelShow);

        panelDetails.setLayout(new javax.swing.BoxLayout(panelDetails, javax.swing.BoxLayout.PAGE_AXIS));

        checkFound.setText("found");
        checkFound.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkFoundStateChanged(evt);
            }
        });
        panelDetails.add(checkFound);

        checkSerum.setText("serum");
        checkSerum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkSerumStateChanged(evt);
            }
        });
        panelDetails.add(checkSerum);

        labelTier.setText("Tier: 00");
        panelDetails.add(labelTier);

        labelSteps.setText("Steps to go: =#0##");
        panelDetails.add(labelSteps);

        buttonToDo.setText("ToDo");
        buttonToDo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                buttonToDoStateChanged(evt);
            }
        });
        panelDetails.add(buttonToDo);

        add(panelDetails);

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void buttonShowStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonShowStateChanged
        this.panelDetails.setVisible(buttonShow.isSelected());
//        this.panelDetails.doLayout();
        this.panelDetails.revalidate();
        this.panelDetails.repaint();
    }//GEN-LAST:event_buttonShowStateChanged

    private void checkFoundStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkFoundStateChanged
        if (species != null&& species.isFound()!= checkFound.isSelected()) {
            species.setFound(checkFound.isSelected());
            BreedingJFrame.getInstance().updateOverview();
        }
    }//GEN-LAST:event_checkFoundStateChanged

    private void checkSerumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkSerumStateChanged
        if (species != null&& species.isSerum()!= checkSerum.isSelected()) {
            species.setSerum(checkSerum.isSelected());
        }
    }//GEN-LAST:event_checkSerumStateChanged

    private void buttonToDoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_buttonToDoStateChanged
        if (species != null && species.isToDo() != buttonToDo.isSelected()) {
            species.setToDo(buttonToDo.isSelected());
            BreedingJFrame.getInstance().fillToDoSpecies();
        }
    }//GEN-LAST:event_buttonToDoStateChanged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        if (species != null) {
            BreedingJFrame.getInstance().setSpecies(species);
        }
    }//GEN-LAST:event_formMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton buttonShow;
    private javax.swing.JToggleButton buttonToDo;
    private javax.swing.JCheckBox checkFound;
    private javax.swing.JCheckBox checkSerum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelSteps;
    private javax.swing.JLabel labelTier;
    private javax.swing.JPanel panelDetails;
    private javax.swing.JPanel panelShow;
    // End of variables declaration//GEN-END:variables

}
